# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8LqbLrgu1JZLnDVARDzZGOQdKHFy3RzJ-3HN4ESsZFClIR_fwn869PZ2RJsfUUdrK1CeoNt8cHfb5UiD-6MTrq2L0IW5w57B806BEluMIERvmrLLKh1vWtiySrP3y0z4BUhAKtvZNQx7NhHfQof_XdfVwcrn1nbuoukhfE6XrV6Kq-1hKh07ZUt3J9P6lLxNwGe5WCh2OnZcm5HouCs8umWUH9loLfLa5UMvzV2Dd5OwP-W2NIUZieylTfRelEcPnGfNluC-efJ1VwkUvIJbVrXd-lh7FXsiKnKolKYOTXrua2021KxwWTxL5npsBQE5BHtKCHBItcJvPiX5Ygo1fMk0NyrSKkPdeBR-K8wBukiNqrKhq6tAmv4hvZMf6qp6yUictfYbPRQFYaJJkMUqrt7XxL5jZDRgSB3bXPl0gs4fOyioRh6dArmJgw2_q9_m0wmaq4sk6n-74tsky-Tf6qsi2bg13AaCvx0Yf6IOAqqmpXuSNJ4pz4Ctfc4feam4OHKx4A-diH9JRT_JNSo45afr6qaJMTk2emZnIG6WdTPSj_wTBdWZ5TI-93uk4HcTBFGBXGZw06uDrOo6ADDOtTbRI3IrAxiXcg47zjpIvVco9en-vU6Y2GSmA7KMTGzqoxhU2xvntvGvcsd3j6UfYlDlsB9lZ3yfnaejR4kcfA-62fJgCgI64sqi540dmDh3h8T8Mmmo0keHfU_OKKtmdOOz4HH1ZaAriSVSOD8Y9ZLqjsyzR1UOeBklI1bkom3sjsjAHjFCDLuyFOPP4I3Y547WZ1AiJBbK3jpEHOp96_ShDXRTxRkLXw2ze0gO7bjaoQ

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

###

# Post Candidates
POST {{Web_HostAddress}}/api/Candidates
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

// CreateOrUpdateCandidateCommand
{
  "firstName": "Jhn",
  "lastName": "Doe",
  "phoneNumber": "+1234567890",
  "email": "john.doe@example.com",
  "callTimeInterval": {
    "date": "2024-05-19T00:22:08.312Z",
    "startTime": "09:00:00",
    "endTime": "17:00:00"
  },
  "linkedInUrl": "https://www.linkedin.com/in/johndoe",
  "gitHubUrl": "https://github.com/johndoe",
  "comment": "Experienced software developer"
}

###

# GET Candidates with pagination
@PageNumber1 = 1
@PageSize1 = 10
GET {{Web_HostAddress}}/api/Candidates?PageNumber={{PageNumber1}}&PageSize={{PageSize1}}
Authorization: Bearer {{BearerToken}}

###

###

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###


# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###
