# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8LqbLrgu1JZLnDVARDzZGOTayBmzdUOBRDEqKR2HKk3XgFE5ZJ4XbGj5FDXp7zhm0eokccMfio6U4gRWvgMgdKqqV58lSOA8D2zeAtNzM2TmYhk1IO8onAsog2AUs86M84Z-JtlOjrZ4Ob1qovi9zSHP33QfAmVEACCf8TV7WoXFkC2eDdjCyK8PuDq2hOIXleC5lW6iCCgyt7KWwVYsfAe_NuJ7YQRQYCkdqslDvFFS3_htJBcp4q3ELMov2f-vtp8ZWDJkDv8CeGv2rVXh_a6rKx2GEpWBiqZDddOnrrngsVS0HbU4NH-HacSGFCXK4uvUqhdfr_tQ7fASOk0s8VECjkarZDQst75MO_DvvsFysD3XlyFiCefrAOFHtOr_RpJxEyORkub9goRrFiVqx_fpIzYhnQbcAEws1AvIn071ETHFEreSh89LPIpUFAcTU5N0Xead7gEEGPVFYkduDKyUvhJwUjLSOOrN6EH7_gqD1R77BLtWHp1DS4d9JW6-6NIDKvo8wQdL4bL0h6GCtEcHyO55HTaMlDt0V426u9PLi8o3229MALfc-eVDwHxK8wkzsvslixXm5ObVZ-P4t-Jt2-gfpDSeW5VwNEDFH4O8v6HotCpOeEnH07iI5F_DTqheM13my7f_qKAOFfOwt4D9Gc-ZtVU5LdWSwMkquAWbrOx6hNlL0UoZr5WkVWhVLAFEFKKaJQ4PTTWLGuDNMZFl0VNlAyT7l-zV64DyszdivhlJSYHhK7ZEO0lBX8pMAYNUN45w1n4GZcRBZLSXoOau4w6qsA7M1AHXZbAOGYmBOO2FqTBotyoQ0jB9ge9MDw

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

###

# Post Candidates
POST {{Web_HostAddress}}/api/Candidates
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

// CreateOrUpdateCandidateCommand
{
  "firstName": "Jhn",
  "lastName": "Doe",
  "phoneNumber": "+1234567890",
  "email": "john.doe@example.com",
  "callTimeInterval": {
    "date": "2024-05-19T00:22:08.312Z",
    "startTime": "09:00:00",
    "endTime": "17:00:00"
  },
  "linkedInUrl": "https://www.linkedin.com/in/johndoe",
  "gitHubUrl": "https://github.com/johndoe",
  "comment": "Experienced software developer"
}

###

# GET Candidates with pagination
@PageNumber1 = 1
@PageSize1 = 5
GET {{Web_HostAddress}}/api/Candidates?PageNumber={{PageNumber1}}&PageSize={{PageSize1}}
Authorization: Bearer {{BearerToken}}

###

###

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###


# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###
